name: Health Check

on:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Get the HTTP status code
              id: get_http_status
              run: |
                code=$(curl http://fmitty.net/ -o /dev/null -w "%{http_code}\n" -s)
                echo "::set-output name=code::$(code)"
            
            - name: Notify to Discord
              id: notify_to_discord
              uses: sarisia/actions-status-discord@v1
              if: always()
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                