name: Health Check

on:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Notify to Discord
              id: notify_to_discord
              uses: sarisia/actions-status-discord@v1
              if: always()
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
